Repository joycehwchan/tabinow, pull requests merged in 2022-11, with the labels that each got.

#3 Added Cloudinary and MapBox
  .gitignore
  Gemfile
  Gemfile.lock
  app/views/layouts/application.html.erb
Labels: enhancement

#7 Added Faker and added the first version of the seeds
  Gemfile
  db/seeds.rb
Labels: enhancement

#8 Started installing and integrating ActionMailer
  Gemfile.lock
  app/mailers/client_mailer.rb
  app/views/client_mailer/Registration.html.erb
  app/views/client_mailer/Registration.text.erb
  config/environments/production.rb
  test/mailers/client_mailer_test.rb
  test/mailers/previews/client_mailer_preview.rb
Labels: enhancement

#12 Worked more on the seeds and changed the database
  Gemfile.lock
  db/migrate/20221121125559_change_data_type_for_phone.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#13 Changed the way users are selected when adding seeds.
  db/seeds.rb
Labels: enhancement

#15 style devise forms and sidebar
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_devise.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/components/_sidebar.scss
  app/javascript/controllers/index.js
  app/javascript/controllers/sidebar_controller.js
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
  app/views/shared/_navbar.html.erb
  app/views/shared/_sidebar.html.erb
Labels: enhancement

#17 Added Stimulus Sortable
  package.json
  yarn.lock
Labels: enhancement

#25 fix sidebar toggle btn
  app/javascript/controllers/sidebar_controller.js
  app/views/shared/_sidebar.html.erb
Labels: bug

#29 Created the basic controller that need some work as we move forward
  app/controllers/itineraries_controller.rb
Labels: enhancement

#37 Days#create
  app/controllers/days_controller.rb
  app/controllers/itineraries_controller.rb
Labels: enhancement

#38 minor css updates
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/components/_sidebar.scss
  app/assets/stylesheets/global/_fonts.scss
  app/views/itineraries/index.html.erb
  app/views/pages/home.html.erb
  app/views/shared/_navbar.html.erb
  app/views/shared/_sidebar.html.erb
Labels: enhancement

#40 Validation, seed, and migration/db fix
  app/models/day.rb
  app/models/itinerary.rb
  app/models/user.rb
  db/migrate/20221122055336_change_referencesin_itineraries.rb
  db/migrate/20221122061428_add_email_and_phone_to_itineraries.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#41 fixed css class-name clashes
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_item_icon.scss
  app/assets/stylesheets/components/_sidebar.scss
  app/assets/stylesheets/config/_bootstrap_variables.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/global/_fonts.scss
Labels: bug

#43 Seed with (some) API, fixed deletion and (some) verification
  Gemfile
  Gemfile.lock
  app/models/user.rb
  db/seeds.rb
Labels: enhancement

#46 Fixed bug with the itinerary show page
  app/controllers/itineraries_controller.rb
  app/policies/itinerary_policy.rb
Labels: bug, enhancement

#50 sidebar and seed fixed error on the days
  app/models/itinerary.rb
  app/views/shared/_sidebar.html.erb
  db/seeds.rb
Labels: bug, enhancement

#51 fix css on itineraries#show
  app/assets/stylesheets/components/_item_icon.scss
  app/assets/stylesheets/pages/_itineraries_show.scss
  app/views/itineraries/_day.html.erb
  app/views/itineraries/_item_icon.html.erb
  app/views/itineraries/show.html.erb
Labels: enhancement

#52 Fixed the API calls in seeds
  db/seeds.rb
Labels: bug, enhancement

#66 Enhance search method
  app/controllers/itineraries_controller.rb
  app/views/shared/_sidebar.html.erb
Labels: enhancement

#71 Updated seeds with real restaurants from API, also updated the DB
  app/models/category.rb
  app/models/content.rb
  app/models/day.rb
  app/models/itinerary.rb
  app/services/activities_api_service.rb
  app/services/hotels_api_service.rb
  app/services/resturants_api_service.rb
  db/migrate/20221121080531_create_contents.rb
  db/migrate/20221123051958_rename_category_to_category_id_in_contents.rb
  db/migrate/20221123052524_create_categories.rb
  db/migrate/20221123075052_change_ratingin_contents.rb
  db/migrate/20221123084037_add_category_to_contents.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#74 Update request form
  app/assets/images/logo.svg
  app/controllers/itineraries_controller.rb
  app/models/itinerary.rb
  app/views/itineraries/_itinerary.html.erb
  app/views/itineraries/_table_row.html.erb
  app/views/pages/_external_request.html.erb
  db/migrate/20221123115507_add_min_budget_and_max_budget_to_itineraries.rb
  db/migrate/20221123123406_add_special_request_to_itineraries.rb
  db/schema.rb
Labels: bug, enhancement

#75 Modified the creation of the categories
  db/seeds.rb
Labels: bug

#76 display category icons and content cards after seed updates
  app/assets/stylesheets/pages/_itineraries_show.scss
  app/views/itineraries/_category_icon.html.erb
  app/views/itineraries/_content.html.erb
  app/views/itineraries/_day.html.erb
Labels: bug

#73 Limited the number of API calls, and refactored code
  db/seeds.rb
Labels: enhancement

#77 Intergraded Bullet
  Gemfile
  Gemfile.lock
  app/services/activities_api_service.rb
  config/environments/development.rb
  config/environments/test.rb
Labels: enhancement

#79 Miss in itineraries#new
  app/controllers/itineraries_controller.rb
  db/seeds.rb
Labels: bug

#80 Added API calls for activities in Seeds
  db/seeds.rb
Labels: enhancement

#82 Accommodation api service
  app/services/accommodation_api_service.rb
  app/services/hotels_api_service.rb
Labels: enhancement

#86 New Category & Item (with accommodation API call)
  app/controllers/itineraries_controller.rb
Labels: enhancement

#87 Remove code that was not relevant
  app/services/accommodation_api_service.rb
Labels: bug

#88 Missed deleting line
  app/views/itineraries/_table_row.html.erb
Labels: bug

#92 Adding restaurants api call
  app/controllers/itineraries_controller.rb
Labels: enhancement

#93 Added API call to Restaurant-Api-Service
  app/services/accommodation_api_service.rb
  app/services/resturant_api_service.rb
  app/services/resturants_api_service.rb
Labels: enhancement

#94 Setting activity api service
  app/services/activities_api_service.rb
  app/services/activity_api_service.rb
Labels: enhancement

#96 Added API Service for Activities in itineraries controller
  app/controllers/itineraries_controller.rb
Labels: enhancement

#99 Added the values from accomodations
  app/controllers/itineraries_controller.rb
  app/services/accommodation_api_service.rb
Labels: enhancement

#108 Fixed the accommodation requests
  app/controllers/itineraries_controller.rb
  app/services/accommodation_api_service.rb
Labels: bug

#110 Accommodations & Restaurants from API
  app/controllers/itineraries_controller.rb
  app/services/accommodation_api_service.rb
  app/services/accommodation_details_api_service.rb
  app/services/restaurant_api_service.rb
Labels: enhancement

#111 Fixed the spelling of 'Accommodation' in the itineraries controller.
  app/controllers/itineraries_controller.rb
Labels: bug

#112 Added activities to the itineraries controller
  app/controllers/itineraries_controller.rb
  app/services/activity_api_service.rb
Labels: enhancement

#113 itinerary validation and creation of itinerary name error fixed
  app/controllers/itineraries_controller.rb
  app/models/itinerary.rb
Labels: bug, enhancement

#114 Add retry to api calls
  app/controllers/itineraries_controller.rb
  app/services/accommodation_api_service.rb
  app/services/accommodation_details_api_service.rb
  app/services/activity_api_service.rb
  app/services/restaurant_api_service.rb
Labels: enhancement

#116 The condition for activity budget was messed up
  app/controllers/itineraries_controller.rb
Labels: bug

#125 Adding api jobs
  Gemfile
  Gemfile.lock
  app/controllers/itineraries_controller.rb
  app/jobs/accommodation_api_job.rb
  app/jobs/activity_api_job.rb
  app/jobs/restaurant_api_job.rb
  bin/sidekiq
  bin/sidekiqmon
  config/application.rb
  config/routes.rb
  config/sidekiq.yml
  db/seeds.rb
  test/jobs/accommodation_api_job_test.rb
  test/jobs/activity_api_job_test.rb
  test/jobs/restaurant_api_job_test.rb
Labels: enhancement

#127 Heroku job fix
  Procfile
  config/initializers/redis.rb
  db/schema.rb
Labels: enhancement

#130 Changed the version of redis and sidkiq
  Gemfile
  Gemfile.lock
Labels: bug

#132 Changed the rating score for accommodations to match the other contents
  app/jobs/accommodation_api_job.rb
Labels: bug

#137 minor css changes
  app/assets/stylesheets/components/_category_icon.scss
  app/assets/stylesheets/components/_content.scss
  app/assets/stylesheets/components/_filter.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/components/_sidebar.scss
  app/assets/stylesheets/pages/_home.scss
  app/assets/stylesheets/pages/_itineraries_show.scss
  app/views/itineraries/_content.html.erb
  app/views/itineraries/_result.html.erb
  app/views/pages/home.html.erb
Labels: enhancement

#139 update views
  app/assets/stylesheets/components/_content.scss
  app/assets/stylesheets/components/_devise.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/pages/_itineraries_show.scss
  app/javascript/controllers/sortable_controller.js
  app/views/devise/registrations/edit.html.erb
  app/views/itineraries/_content.html.erb
  app/views/itineraries/_create_modal.html.erb
  app/views/itineraries/_edit_modal.html.erb
  app/views/itineraries/_result.html.erb
  app/views/itineraries/_sidebar.html.erb
  app/views/itineraries/_table_row.html.erb
  app/views/itineraries/index.html.erb
  app/views/shared/_navbar.html.erb
Labels: enhancement

#140 added more homepage content
  app/assets/images/demo.png
  app/assets/stylesheets/components/_content.scss
  app/assets/stylesheets/pages/_home.scss
  app/assets/stylesheets/pages/_itineraries_show.scss
  app/javascript/application.js
  app/javascript/controllers/index.js
  app/javascript/typewriter.js
  app/views/pages/_section_about.html.erb
  app/views/pages/_section_reviews.html.erb
  app/views/pages/_section_steps.html.erb
  app/views/pages/home.html.erb
  package.json
  yarn.lock
Labels: enhancement

#142 Moved API calls to model and moved API-keys to ENV
  app/controllers/itineraries_controller.rb
  app/models/itinerary.rb
  app/services/accommodation_api_service.rb
  app/services/accommodation_details_api_service.rb
  app/services/activity_api_service.rb
  app/services/restaurant_api_service.rb
Labels: enhancement

#143 Changed the functions so they work from the Model
  app/jobs/accommodation_api_job.rb
  app/jobs/activity_api_job.rb
  app/jobs/restaurant_api_job.rb
  app/models/itinerary.rb
  app/services/accommodation_api_service.rb
Labels: bug, enhancement

#144 Added IMG to Accommodation
  app/jobs/accommodation_api_job.rb
  app/models/content.rb
Labels: enhancement

#146 Added Images to the Accommodation
  app/jobs/accommodation_api_job.rb
  app/services/accommodation_details_api_service.rb
Labels: enhancement

#148 Adding images to restaurants
  app/jobs/activity_api_job.rb
  app/jobs/restaurant_api_job.rb
Labels: enhancement

#149 Attaching images to the activities
  app/jobs/activity_api_job.rb
Labels: enhancement

#151 Updated the seeds
  db/seeds.rb
Labels: enhancement

#153 fix search + filter bug (stimulus)
  app/javascript/controllers/filter_controller.js
  app/javascript/controllers/index.js
  app/javascript/controllers/search_controller.js
  app/views/itineraries/_result.html.erb
  app/views/itineraries/_results.html.erb
  app/views/itineraries/show.html.erb
Labels: bug

#154 Same hotel on everyday when generated
  app/jobs/accommodation_api_job.rb
  app/models/itinerary.rb
Labels: bug, enhancement

#156 Create DB table for unused Contents
  db/migrate/20221128072103_create_unused_contents.rb
Labels: enhancement

#155 Create DB table for unused Categories
  db/migrate/20221128071819_create_unused_categories.rb
Labels: enhancement

#157 Saving unused categories & contents
  app/jobs/accommodation_api_job.rb
  db/migrate/20221128071819_create_unused_categories.rb
  db/migrate/20221128074251_create_unused_contents.rb
  db/schema.rb
Labels: enhancement

#159 Saving unused contents (Accommodation, Restaurants & Activities)
  app/jobs/accommodation_api_job.rb
  app/jobs/activity_api_job.rb
  app/jobs/restaurant_api_job.rb
  app/models/unused_content.rb
  db/schema.rb
Labels: enhancement

#177 Add coordinates to unused contents
  app/controllers/days_controller.rb
  app/jobs/accommodation_api_job.rb
  app/jobs/afternoon_api_job.rb
  app/jobs/morning_api_job.rb
  app/views/itineraries/_map.html.erb
  db/migrate/20221130002218_add_coordinates_to_unused_contents.rb
  db/schema.rb
Labels: enhancement

#180 Update itinerary
  app/controllers/days_controller.rb
  app/jobs/accommodation_api_job.rb
Labels: bug, enhancement

#182 Fixed migration and updated seeds
  db/migrate/20221130030245_remove_position_from_categories.rb
  db/schema.rb
  db/seeds.rb
Labels: bug, enhancement

#183 Enhance mapbox
  app/assets/stylesheets/components/_content.scss
  app/assets/stylesheets/components/_map.scss
  app/assets/stylesheets/pages/_itineraries_show.scss
  app/controllers/itineraries_controller.rb
  app/javascript/controllers/map_controller.js
  app/views/itineraries/_map_marker.html.erb
  app/views/itineraries/_map_popup.html.erb
  app/views/itineraries/_overview_sidebar.html.erb
Labels: enhancement

#184 display correct content(markers) in map
  app/assets/stylesheets/pages/_itineraries_show.scss
  app/controllers/itineraries_controller.rb
  app/views/itineraries/_map_popup.html.erb
  app/views/itineraries/_overview_sidebar.html.erb
Labels: bug

#185 minor changes on container flex
  app/assets/stylesheets/components/_map.scss
  app/assets/stylesheets/pages/_itineraries_show.scss
  app/assets/stylesheets/pages/_start.scss
  app/javascript/controllers/map_controller.js
Labels: enhancement

#189 Adding interests to itineraries (and using them to customize the trip)
  app/assets/stylesheets/components/_form.scss
  app/controllers/itineraries_controller.rb
  app/jobs/afternoon_api_job.rb
  app/jobs/morning_api_job.rb
  app/services/activity_api_service.rb
  app/views/itineraries/_create_modal.html.erb
  app/views/itineraries/_edit_modal.html.erb
  app/views/itineraries/_itinerary.html.erb
  app/views/itineraries/_sidebar.html.erb
  app/views/itineraries/_table_row.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/_external_request.html.erb
  app/views/pages/start.html.erb
  db/migrate/20221130052330_remove_special_request_from_itineraries.rb
  db/migrate/20221130052505_add_interests_to_itineraries.rb
  db/schema.rb
  db/seeds.rb
Labels: bug, enhancement
